const WEBSITE_BASE_URL = import.meta.env.VITE_WEBSITE_URL;
const TUTORIALS_BASE_URL = "/tutorials";
export const WEBSITE_ROUTES = Object.freeze({
  HOME: WEBSITE_BASE_URL,
  FEATURES: `${WEBSITE_BASE_URL}/#features`,
  FAQ: `${WEBSITE_BASE_URL}/#faq`,
  CONTACT: `${WEBSITE_BASE_URL}/#contact`,
  TUTORIALS: TUTORIALS_BASE_URL,
  SIGN_IN: import.meta.env.VITE_LOGIN_URL,
  LIVE_DEMO: `${WEBSITE_BASE_URL}/#contact`,
  TUTORIAL_ACCOUNT_SETUP: `/account-setup`,
  TUTORIAL_CURRENT_YEAR_SETUP: `configure-current-year`,
  TUTORIAL_MEMBERSHIP_FEE_SETUP: `membership-fee-setup`,
  TUTORIAL_ORGANISATION_MANAGEMENT: `organisation-management`,
  TUTORIAL_USER_MANAGEMENT: `user-management`,
  TUTORIAL_USER_REGISTRATION: `user-registration`,
  TUTORIAL_PAYMENT_CATEGORY_MANAGEMENT: `payment-category-management`,
  TUTORIAL_PAYMENT_ITEM_MANAGEMENT: `payment-item-management`,
  TUTORIAL_EXPENDITURE_MANAGEMENT: `expenditure-management`,
  TUTORIAL_EXPENDITURE_ITEM_MANAGEMENT: `expenditure-item-management`,
  TUTORIAL_EXPENDITURE_ITEM_DETAIL_MANAGEMENT: `expenditure-item-detail-management`,
  TUTORIAL_INCOME_MANAGEMENT: `income-management`,
  TUTORIAL_SAVINGS_MANAGEMENT: `savings-management`,
  TUTORIAL_SPONSHOR_MANAGEMENT: `sponsor-management`,
  TUTORIAL_REPORT_MANAGEMENT: `report-management`,
  TUTORIAL_BALANCE_SHEET: `balance-sheet`,
  TUTORIAL_CONTRIBUTION_MANAGEMENT: `contribution-management`,
  TUTORIAL_INVITE_COLLABORATOR: `invite-collaborator`,
  TUTORIAL_ROLE_MANAGEMENT: `role-management`,
  TUTORIAL_LOGIN: `login`,
});
